title: OOP '26
description: Pemrograman Berorientasi Objek Gasal 2026 - S1 Kecerdasan Artifisial, Universitas Negeri Surabaya
theme: just-the-docs

url: "https://oop-ai26.github.io"
baseurl: "/Praktikum-Gasal-2026"
permalink: pretty
timezone: Asia/Jakarta
color_scheme: wider

search_enabled: true
heading_anchors: true
nav_enabled: true
nav_sort: case_sensitive

aux_links:
  Dark Mode:
    - "#"
  "Course Info":
    - "https://oop-ai26.github.io/Praktikum-Gasal-2026/course-info/"
  "Staff":
    - "https://oop-ai26.github.io/Praktikum-Gasal-2026/staff/"
aux_links_new_tab: false

back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Object-Oriented Programming '26 - TAs"

sass:
  quiet_deps: true
  silence_deprecations: [import]

exclude:
  - assignment/assignment1/studycase1/variants
  - assignment/assignment1/studycase1/description.md
  - assignment/assignment1/homework/variants
  - assignment/assignment1/homework/description.md
  - assignment/assignment2/studycase2/variants
  - assignment/assignment2/studycase2/description.md
  - assignment/assignment2/homework/variants
  - assignment/assignment2/homework/description.md
  - assignment/assignment3/studycase3/variants
  - assignment/assignment3/studycase3/description.md
  - assignment/assignment3/homework/variants
  - assignment/assignment3/homework/description.md
  - assignment/assignment4/studycase4/variants
  - assignment/assignment4/studycase4/description.md
  - assignment/assignment4/homework/variants
  - assignment/assignment4/homework/description.md

callouts:
  warning:
    title: Warning
    color: red
  highlight:
    color: yellow
